#!/usr/bin/python

# This file is part of Spacetime.
#
# Copyright (C) 2010-2012 Leiden University.
# Written by Sander Roobol.
#
# Spacetime is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Spacetime is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import sys

try:
	import spacetime.gui.main
except ImportError:
	sys.path.append('lib')
	try:
		import spacetime.gui.main
	except ImportError:
		sys.stderr.write("Unable to load Spacetime module spacetime.app\n"
			"Please install Spacetime in your PYTHONPATH or in ./lib\n")
		exit(1)
	else:
		sys.stderr.write("Loading Spacetime from ./lib\n")

app = spacetime.gui.main.App()
app.run()
