#!/usr/bin/python

# This file is part of Spacetime.
#
# Copyright (C) 2010-2014 Leiden University.
# Written by Sander Roobol.
#
# Spacetime is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# Spacetime is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import sys
import logging

if '--debug' in sys.argv:
	logging.basicConfig(level=logging.DEBUG)
else:
	logging.basicConfig(level=logging.WARNING)
logger = logging.getLogger(__name__)

try:
	import spacetime.gui.main
except ImportError:
	sys.path.append('lib')
	try:
		import spacetime.gui.main
	except ImportError:
		logger.error("Unable to load Spacetime module spacetime.app\n"
			"Please install Spacetime in your PYTHONPATH or in ./lib")
		sys.exit(1)
	else:
		logger.info("Loading Spacetime from ./lib")

app = spacetime.gui.main.App()
context = app.context
del sys, logging, logger, spacetime, app
context.app.run()
